### PR TITLE
Changed testing unit to jasmine

### LINKED ISSUE #30: Setup unit testing with jasmine

### PR DESCRIPTION
**Pull request by Mikazakaryan**
i don't know what to write sorry @fuzzytern ;)

Resolves  #30

### CODE REVIEW

**Comment by fuzzytern** [comment]
Right @rubpat. @Mikazakaryan could you fix this as long as the irrelevant PR description and actually add a basic unit test as described in #30 ?

**Comment by Mikazakaryan** [comment]
i can, but not yet now i'm doing modules

**Comment by fuzzytern** [comment]
@Mikazakaryan Use feature branches!!

**Comment by fuzzytern** [comment]
@rubpat please use the « request changes » review feature appropriately. « Poor commit message » is a  jugement and does not guide the original poster towards the steps 

If you'd like them to learn about writing good commit message, tell so, and point them towards a good reference for doing so such as [Chris Beams' seven rules to writing commit messages](http://chris.beams.io/posts/git-commit/#seven-rules).

**Pull request closed without merging**
