### PR TITLE
Modularised timer with error

### PR DESCRIPTION
**Pull request by Mikazakaryan**
@fuzzytern look at this please

### CODE REVIEW

**Comment by Mikazakaryan** [comment]
when it will work i will separate it to many modules

**Comment by hayko1995** [comment]
ok

**Comment by fxfactorial** [comment]
@Mikazakaryan Try to start writing code correctly from the beginning. Programmers have a bad habit of saying I will do this later and then never doing it.

**Comment by fuzzytern** [comment]
@Mikazakaryan plus, this is based of your other testing-related branch that hasn't been merged. Please rebase your work off upstream/master without commit 73bb6d5.

Side note: sending me broken code for me to correct does little to building up your knowledge and understanding of how things work. Instead, if you have knowledge gaps about modules and objects, try simple things: fire up a REPL, write dead-simple script and make them run. Only if you realize your mistakes by yourself will you remember them. Closing for now.

**Pull request closed without merging**
